### ISSUE TITLE
ฺีBug Report

### ISSUE THREAD

**Issue by gomonx** [Adel-Qusay/Codeigniter-4-CRUD-generator#11]
in View Template
- Don't Set DataTable option 'scrollCollapse'  it to 'True'. Bug! Action Button not floating
- please Set it to 'False'

in core/class.engine
	public function getBetween($string, $start, $end){
		$string = ' ' . $string;
		$ini = strpos($string, $start);
		if ($ini == 0) return '';
		$ini += strlen($start);
		$len = strpos($string, $end, $ini) - $ini;
		//fix bug: example >> decimal(8,2)
		$result = substr($string, $ini, $len);
		$ini = strpos($result, ',');
		if($ini != false){
			$result = substr($result,0,$ini);
		}
		return $result;
	}

**Comment by Adel-Qusay** [comment]
Done
