### ISSUE TITLE
missed a placeholder in controller template

### ISSUE THREAD

**Issue by boban-dj** [Adel-Qusay/Codeigniter-4-CRUD-generator#3]
@Adel, great autocrud.
you missed a placeholdername in /mvc_templates/en_Controler.tpl.php
change
`67:	$data = $this->sourcesModel->where('@@@primaryKey@@@' ,$id)->first();`
to
`67:  $data = $this->@@@modelName@@@->where('@@@primaryKey@@@' ,$id)->first();`

**Comment by marioacalderon** [comment]
hi, does this work with join sql?

**Comment by Adel-Qusay** [comment]
> 
> 
> @Adel, great autocrud.
> you missed a placeholdername in /mvc_templates/en_Controler.tpl.php
> change
> `67: $data = $this->sourcesModel->where('@@@primaryKey@@@' ,$id)->first();`
> to
> `67: $data = $this->@@@modelName@@@->where('@@@primaryKey@@@' ,$id)->first();`

Corrected ... Thanks

**Comment by michaelaous** [comment]
Hi,
am having problems with the functionality of this generator can anyone help?

**Comment by boban-dj** [comment]
Make a new issue and explain what your problem is
