### ISSUE TITLE
Deprecated: Function get_magic_quotes_gpc() 

### ISSUE THREAD

**Issue by 007amitgarg** [Adel-Qusay/Codeigniter-4-CRUD-generator#5]
Deprecated: Function get_magic_quotes_gpc() is deprecated in D:\php74\xampp\htdocs\Codeigniter-4-CRUD-generator-main\core\class.engine.php on line 331

in browser console error is : Uncaught SyntaxError: Unexpected token < in JSON at position 0

**Comment by herrrilke** [comment]
ran into this after switching from PHP7.3 to PHP7.4, too.

until PHP 8 you could use in #331

`$magic_quotes = (bool)@get_magic_quotes_gpc();`
